### Importando excel inicial de sessões

In [11]:
vendor = 'estudio_amelia'
invoicing = '2026-08'
file = '../files/aulas-2026-09-03.xlsx'

In [12]:
from reconciliation import get_sessions

df_sessions = get_sessions(invoicing, file)
df_sessions

,customer,service,minutes,status_row,status_type,month,done
0,juliana_franco,aula/canto,60,ok,realizada/reposicao,2026-07,5
1,timbere_nogueira,aula/canto,60,ok,realizada/reposicao,2026-07,5
2,viviane_cerqueira,aula/canto,60,ok,realizada/reposicao,2026-07,5
3,juliana_franco,aula/canto,60,ok,realizada/reposicao,2026-08,4
4,timbere_nogueira,aula/canto,60,ok,realizada/reposicao,2026-08,4
5,camila_merigui,aula/canto,60,ok,realizada/reposicao,2026-07,3
6,camila_merigui,aula/piano,60,ok,realizada/reposicao,2026-07,3
7,julia_(florida),aula/canto,45,ok,realizada/reposicao,2026-07,3
8,carol_teclarte,aula/canto,45,ok,realizada/reposicao,2026-07,3
9,julia_(florida),aula/canto,45,ok,realizada/reposicao,2026-08,3
10,viviane_cerqueira,aula/canto,60,ok,realizada/reposicao,2026-08,3
11,sophia_lopes,aula/canto,60,ok,realizada/reposicao,2026-07,2
12,giovanna_boni,aula/canto,60,ok,realizada/reposicao,2026-07,2
13,rui_miranda,aula/canto,60,ok,realizada/reposicao,2026-07,2
14,miriam,aula/canto,60,ok,realizada/reposicao,2026-07,2
15,ana_flavia,aula/canto,60,ok,realizada/reposicao,2026-08,2
16,camila_merigui,aula/canto,60,ok,realizada/reposicao,2026-08,2
17,carol_teclarte,aula/canto,45,ok,realizada/reposicao,2026-08,2
18,miriam,aula/canto,60,ok,realizada/reposicao,2026-08,2
19,camila_merigui,aula/piano,60,ok,realizada/reposicao,2026-08,2
20,sophia_lopes,aula/canto,30,ok,realizada/reposicao,2026-08,2
21,ana_flavia,aula/canto,60,ok,realizada/reposicao,2026-07,1
22,sophia_lopes,aula/canto,30,ok,realizada/reposicao,2026-07,1
23,carol_teclarte,aula/canto,60,ok,realizada/reposicao,2026-07,1
24,rui_miranda,aula/canto,60,ok,realizada/reposicao,2026-08,1
25,giovanna_boni,aula/canto,45,ok,realizada/reposicao,2026-08,1
26,carol_teclarte,aula/canto,60,ok,realizada/reposicao,2026-08,1
27,andressa_lino,aula/canto,30,ok,realizada/reposicao,2026-08,1
28,miriam,aula/canto,30,ok,realizada/reposicao,2026-08,1
29,giovanna_boni,aula/canto,60,ok,realizada/reposicao,2026-08,1
30,nicoli_bozzella,aula/canto,60,ok,realizada/reposicao,2026-08,1
31,stefanie,aula/canto,60,ok,realizada/reposicao,2026-07,1

In [13]:
from reconciliation import get_invoices

df_invoices = get_invoices(vendor=vendor, invoicing=invoicing)
df_invoices

,customer,invoicing,payment,amount,description,preview,price,month,minutes,service,status_row
0,carol_teclarte,2026-08-02,paid,392,aulas de canto de 45 minutos em agosto de 2026,4,98,2026-08,45.0,aula/canto,ok
1,camila_merigui,2026-08-02,paid,588,aulas de canto de 60 minutos em julho de 2026,3,98,2026-07,60.0,aula/canto,ok
2,camila_merigui,2026-08-02,paid,588,aulas de piano de 60 minutos em julho de 2026,3,98,2026-07,60.0,aula/piano,ok
3,rui_miranda,2026-08-02,paid,240,aulas de canto de 60 minutos em agosto de 2026,2,120,2026-08,60.0,aula/canto,ok
4,sophia_lopes,2026-08-02,paid,360,aulas de canto de 30 minutos em julho de 2026,2,60,2026-07,30.0,aula/canto,ok
5,sophia_lopes,2026-08-02,paid,360,aulas de canto de 60 minutos em julho de 2026,2,120,2026-07,60.0,aula/canto,ok
6,giovanna_boni,2026-08-02,paid,220,aulas de canto de 60 minutos em julho de 2026,2,110,2026-07,60.0,aula/canto,ok
7,miriam,2026-08-02,paid,220,aulas de canto de 60 minutos em julho de 2026,2,110,2026-07,60.0,aula/canto,ok
8,andressa_lino,2026-08-05,paid,70,aula de canto de 30 minutos em 27/08/2026,1,70,2026-08,30.0,aula/canto,ok
9,juliana_franco,2026-08-02,paid,440,aulas de canto de 60 minutos em julho de 2026,4,110,2026-07,60.0,aula/canto,ok
10,andressa_lino,2026-08-05,paid,70,aula de canto de 30 minutos em 20/08/2026,1,70,2026-08,30.0,aula/canto,ok
11,julia_(florida),2026-08-02,paid,392,aulas de canto de 45 minutos em julho de 2026,4,98,2026-07,45.0,aula/canto,ok
12,nicoli_bozzella,2026-08-17,paid,240,aulas de canto de 60 minutos em agosto de 2026,2,120,2026-08,60.0,aula/canto,ok
13,timbere_nogueira,2026-08-02,paid,440,aulas de canto de 60 minutos em agosto de 2026,4,110,2026-08,60.0,aula/canto,ok
14,sandra_oliveira,2026-08-01,paid,100,edição de músicas para aula em 01/08/2026,1,100,2026-08,NaN,NaN,error
15,ana_flavia,2026-08-02,paid,220,aulas de canto de 60 minutos em julho de 2026,2,110,2026-07,60.0,aula/canto,ok
16,andressa_lino,2026-08-20,paid,70,hora adicional de aulas de canto de 30 minutos...,1,70,2026-08,30.0,aula/canto,ok
17,sheila_silva,2026-08-28,paid,150,aulas de canto avulsa de 60 minutos prevista p...,1,150,2026-09,60.0,aula/canto,ok
18,helena_batista,2026-08-27,paid,210,aulas de canto de 30 minutos previstas para os...,3,70,2026-08,30.0,aula/canto,ok
19,viviane_cerqueira,2026-08-02,paid,440,aulas de canto de 60 minutos em agosto de 2026,4,110,2026-08,60.0,aula/canto,ok

In [14]:
from reconciliation import reconciliate
df_rec = reconciliate(df_invoices, df_sessions)

df_rec

,status_row,month,customer,service,minutes,preview,done,balance
0,ok,2026-08,carol_teclarte,aula/canto,45.0,4,2,2
1,ok,2026-07,camila_merigui,aula/canto,60.0,3,3,0
2,ok,2026-07,camila_merigui,aula/piano,60.0,3,3,0
3,ok,2026-08,rui_miranda,aula/canto,60.0,2,1,1
4,ok,2026-07,sophia_lopes,aula/canto,30.0,2,1,1
5,ok,2026-07,sophia_lopes,aula/canto,60.0,2,2,0
6,ok,2026-07,giovanna_boni,aula/canto,60.0,2,2,0
7,ok,2026-07,miriam,aula/canto,60.0,2,2,0
8,ok,2026-08,andressa_lino,aula/canto,30.0,1,1,0
9,ok,2026-07,juliana_franco,aula/canto,60.0,4,5,-1
10,ok,2026-08,andressa_lino,aula/canto,30.0,1,1,0
11,ok,2026-07,julia_(florida),aula/canto,45.0,4,3,1
12,ok,2026-08,nicoli_bozzella,aula/canto,60.0,2,1,1
13,ok,2026-08,timbere_nogueira,aula/canto,60.0,4,4,0
14,error,2026-08,sandra_oliveira,NaN,NaN,1,0,1
15,ok,2026-07,ana_flavia,aula/canto,60.0,2,1,1
16,ok,2026-08,andressa_lino,aula/canto,30.0,1,1,0
17,ok,2026-09,sheila_silva,aula/canto,60.0,1,0,1
18,ok,2026-08,helena_batista,aula/canto,30.0,3,0,3
19,ok,2026-08,viviane_cerqueira,aula/canto,60.0,4,3,1

In [15]:
df_rec[(df_rec['month'] == '2026-07') & (df_rec['status_row'] == 'ok')]

,status_row,month,customer,service,minutes,preview,done,balance
1,ok,2026-07,camila_merigui,aula/canto,60.0,3,3,0
2,ok,2026-07,camila_merigui,aula/piano,60.0,3,3,0
4,ok,2026-07,sophia_lopes,aula/canto,30.0,2,1,1
5,ok,2026-07,sophia_lopes,aula/canto,60.0,2,2,0
6,ok,2026-07,giovanna_boni,aula/canto,60.0,2,2,0
7,ok,2026-07,miriam,aula/canto,60.0,2,2,0
9,ok,2026-07,juliana_franco,aula/canto,60.0,4,5,-1
11,ok,2026-07,julia_(florida),aula/canto,45.0,4,3,1
15,ok,2026-07,ana_flavia,aula/canto,60.0,2,1,1

In [16]:
df_rec[(df_rec['month'] == '2026-08') & (df_rec['status_row'] == 'ok')]

,status_row,month,customer,service,minutes,preview,done,balance
0,ok,2026-08,carol_teclarte,aula/canto,45.0,4,2,2
3,ok,2026-08,rui_miranda,aula/canto,60.0,2,1,1
8,ok,2026-08,andressa_lino,aula/canto,30.0,1,1,0
10,ok,2026-08,andressa_lino,aula/canto,30.0,1,1,0
12,ok,2026-08,nicoli_bozzella,aula/canto,60.0,2,1,1
13,ok,2026-08,timbere_nogueira,aula/canto,60.0,4,4,0
16,ok,2026-08,andressa_lino,aula/canto,30.0,1,1,0
18,ok,2026-08,helena_batista,aula/canto,30.0,3,0,3
19,ok,2026-08,viviane_cerqueira,aula/canto,60.0,4,3,1

In [17]:
from reconciliation import extras

df_extras = extras(df_invoices, df_sessions, invoicing_month=invoicing)
df_extras

          customer     service  minutes  done
11   giovanna_boni  aula/canto       45     1
12  carol_teclarte  aula/canto       60     1
16          miriam  aula/canto       30     1