### Importando excel inicial de sessões

In [1]:
vendor = 'estudio_amelia'
invoicing = '2026-08'
file = '../files/aulas-2026-09-03.xlsx'

In [2]:
from reconciliation import get_sessions

df_sessions = get_sessions(invoicing, file)

In [3]:
from reconciliation import get_invoices

df_invoices = get_invoices(vendor=vendor, invoicing=invoicing)

In [4]:
from reconciliation import reconciliate
df_rec = reconciliate(df_invoices, df_sessions)

In [8]:
from reconciliation import extras

df_extras = extras(df_invoices, df_sessions, invoicing_month=invoicing)
df_extras

          customer     service  minutes  done
11   giovanna_boni  aula/canto       45     1
12  carol_teclarte  aula/canto       60     1
16          miriam  aula/canto       30     1

In [5]:
df_rec[(df_rec['month'] == '2026-07') & (df_rec['status_row'] == 'ok') & (df_rec['preview'] != df_rec['done']) ]

,status_row,month,customer,service,minutes,payment,preview,done,balance
4,ok,2026-07,sophia_lopes,aula/canto,30.0,paid,2,1,1
9,ok,2026-07,juliana_franco,aula/canto,60.0,paid,4,5,-1
11,ok,2026-07,julia_(florida),aula/canto,45.0,paid,4,3,1
15,ok,2026-07,ana_flavia,aula/canto,60.0,paid,2,1,1

In [6]:
df_rec[(df_rec['month'] == '2026-08') & (df_rec['status_row'] == 'ok') & (df_rec['preview'] != df_rec['done'])]

,status_row,month,customer,service,minutes,payment,preview,done,balance
0,ok,2026-08,carol_teclarte,aula/canto,45.0,paid,4,2,2
3,ok,2026-08,rui_miranda,aula/canto,60.0,paid,2,1,1
12,ok,2026-08,nicoli_bozzella,aula/canto,60.0,paid,2,1,1
18,ok,2026-08,helena_batista,aula/canto,30.0,paid,3,0,3
19,ok,2026-08,viviane_cerqueira,aula/canto,60.0,paid,4,3,1